spring:
  application:
    name: menuguru
  profiles:
    default: docker
  jackson:
    deserialization:
      fail-on-unknown-properties: true     
server:
  servlet:
    context-path: "/menuguru-orders/v1"      
---
spring:
  config:
    activate:
      on-profile:
      - docker
  
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver  
    url: jdbc:mysql://${MYSQL_URL}/menuguru
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_URL}
      database: menuguru
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  payment:
    userId: ${PAYMENT_USER_ID}
    accessToken: ${PAYMENT_ACCESS_TOKEN}    
    hostWebhook: ${PAYMENT_HOST_WEBHOOK}   
  customer:
    serviceUrl: ${MENUGURU_CUSTOMER_SERVICE_URL}   