apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuguru-order-deployment
  labels:
    menuguru.fiapprj.perisatto.com/name: order-service
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      menuguru.fiapprj.perisatto.com/name: order-service
  template:
    metadata:
      name: menuguru-order-deployment
      labels:
        menuguru.fiapprj.perisatto.com/name: order-service
    spec:           
      containers:
        - name: menuguru-service
          image: rperisatto/menuguru-order:{{ .Values.image.tag }}
          env:
            - name: MYSQL_URL
              valueFrom:
                configMapKeyRef:
                  name: menuguru-order-config
                  key: mysql_url
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: menuguru-order-secret
                  key: mysql_user      
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: menuguru-order-secret
                  key: mysql_password
            - name: PAYMENT_USER_ID
              valueFrom:
                secretKeyRef:
                  name: menuguru--order-secret
                  key: payment_user_id
            - name: PAYMENT_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: menuguru-order-secret
                  key: payment_access_token
            - name: PAYMENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: menuguru-order-config
                  key: payment_host
            - name: PAYMENT_HOST_WEBHOOK
              valueFrom:
                configMapKeyRef:
                  name: menuguru-order-config
                  key: payment_host_webhook
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: menuguru-order-config
                  key: mongodb_url
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: menuguru-order-secret
                  key: mongodb_user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: menuguru-order-secret
                  key: mongodb_password 
            - name: MENUGURU_CUSTOMER_SERVICE_URL
              valueFrom:
                  configMapKeyRef:
                    name: menuguru-order-config
                    key: customer_service_host
            - name: PRODUCT_CUSTOMER_SERVICE_URL
              valueFrom:
                  configMapKeyRef:
                    name: menuguru-order-config
                    key: product_service_host					                         
          ports:
            - containerPort: 8080      
          readinessProbe:
            httpGet:
              path: /menuguru-orders/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /menuguru-orders/v1/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 60