apiVersion: v1
kind: Secret
metadata:
  name: menuguru-order-secret
data:
  mysql_user: {{ .Values.mysql_user }}
  mysql_password: {{ .Values.mysql_password }}
  payment_user_id: "{{ .Values.payment_userId }}"
  payment_access_token: {{ .Values.payment_accessToken }}
  mongodb_user: {{ .Values.mongodb_user }}
  mongodb_password: {{ .Values.mongodb_password }}